---
author: 'Thomas Battram'
date: 'December 2020' # Month and year of submission
title: "Complex trait architecture through the lens of epigenome-wide association studies"
university: "University of Bristol"
faculty: "Health Sciences"
school: "Bristol Medical School"
group: "MRC Integrative Epidemiology Unit"
degree: "Population Health Sciences"
logo: figure/index/UoBcrest.pdf # logo will only show on PDF
bibliography: bib/thesis.bib # location of your bibliography 
csl: csl/american-journal-of-epidemiology.csl # location of your referencing style 
knit: "bookdown::render_book" # doesnt need changing 
site: bookdown::bookdown_site # doesnt need changing 
toc-depth: 4 # change for the depth of the table of contents - 1 gives two levels, 2 gives 3 levels etc...
lot: true 
lof: true
space_between_paragraphs: true
graphics: yes
fig_caption: true
header-includes:
    \usepackage{tikz}
    \usepackage{booktabs}
    \usepackage{longtable}
    \usepackage{siunitx}
    \pagestyle{plain}
output: 
  thesisdown::thesis_pdf: default
#  thesisdown::thesis_gitbook: default
#  thesisdown::thesis_word: default
#  thesisdown::thesis_epub: default
geometry: "left=1cm, right=1cm, top=1cm, bottom=1cm" # This doesn't work
abstract: |
  `r if(knitr:::is_latex_output()) paste(readLines("00-abstract.Rmd"), collapse = '\n  ')`
acknowledgements: |
  `r if(knitr:::is_latex_output()) paste(readLines("00-acknowledgements.Rmd"), collapse = '\n  ')`
publications: |
  `r if(knitr:::is_latex_output()) paste(readLines("00-publications.Rmd"), collapse = '\n  ')`
declaration: |
  `r if(knitr:::is_latex_output()) paste(readLines("00-declaration.Rmd"), collapse = '\n  ')`
abbreviations: |
  `r if(knitr:::is_latex_output()) paste(readLines("00-abbreviations.Rmd"), collapse = '\n  ')`
---

```{r thesis-setup, include=FALSE}
# you need these packages
if(!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")
if(!require(thesisdown))
  devtools::install_github("ismayc/thesisdown")
library(thesisdown)
if(!require(kableExtra))
  devtools::install_github("haozhu233/kableExtra")
library(kableExtra)
if(!require(tinytex))
  devtools::install_github('yihui/tinytex')
library(tinytex)
options(tinytex.verbose = TRUE)
if(!require(flextable))
  devtools::install_github("davidgohel/flextable")
library(flextable)

# extra packages I use in a lot of chunks
library(tidyverse) # simple tidying of data
library(RColorBrewer) # customising plot colours
library(gridExtra) # plotting multiple graphs on the same page
library(readxl) # reading in excel spreadsheets
library(xfun) # misc functions including numbers_to_words()

# this will allow us to make word documents with relatively ok tables
doc.type <- knitr::opts_knit$get('rmarkdown.pandoc.to')

# set figure and table paths
fig_path <- "figure"
tab_path <- "data"
stopifnot(file.exists(fig_path) | file.exists(tab_path))

# some useful functions
source("chunks/useful_functions.R", local = knitr::knit_global())

```

```{r setoptions, eval = TRUE, echo = FALSE}
opts_chunk$set(echo = FALSE, 
            warning = FALSE, 
            message = TRUE, 
            cache = FALSE, 
            dpi = 300,
            fig.align = "center",
            out.width = "100%")
```


